-- Tabla de Pedidos
create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  numero_pedido text not null unique, -- Ej: Pedido-0001
  cliente_id uuid not null references public.clientes(id),
  fecha timestamp with time zone default now(),
  total numeric(10, 2) not null default 0,
  estado text not null default 'Pendiente' -- Pendiente, Pagado, Cancelado, Completado
);

-- Tabla de Detalles de Pedido (para soportar múltiples productos por pedido si fuera necesario)
create table if not exists public.pedido_detalles (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.pedidos(id) on delete cascade,
  producto_id bigint references public.productos(id),
  oferta_id bigint references public.ofertas(id),
  cantidad integer not null default 1,
  precio_unitario numeric(10, 2) not null
);

-- Función para generar el número de pedido automático Pedido-XXXX
create or replace function public.generar_numero_pedido()
returns trigger as $$
declare
  nuevo_numero text;
begin
  -- Corregimos el casting de lpad para evitar el error 42883
  select 'Pedido-' || lpad((coalesce(count(*), 0) + 1)::text, 4, '0')
  from public.pedidos into nuevo_numero;

  new.numero_pedido := nuevo_numero;
  return new;
end;
$$ language plpgsql;

-- Eliminamos el trigger si ya existe para poder recrearlo
drop trigger if exists tr_generar_numero_pedido on public.pedidos;

create trigger tr_generar_numero_pedido
before insert on public.pedidos
for each row
execute function public.generar_numero_pedido();
