create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  descripcion text
);

create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  precio numeric(10, 2) not null,
  stock integer not null,
  fecha_vencimiento date not null,
  imagen_url text,
  imagen_path text,
  categoria_id bigint not null references public.categorias(id)
);

create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  nombre text not null,
  correo text not null unique check (correo ~ '^[^@]+@savebite\.com$'),
  password_hash text not null,
  rol text not null default 'Operador',
  genero text,
  es_administrador boolean not null default false,
  estado text not null default 'Activo',
  foto_url text,
  foto_path text
);

insert into storage.buckets (id, name, public)
values ('productos', 'productos', true)
on conflict (id) do update set public = true;

insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do update set public = true;

create table if not exists public.ofertas (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descuento numeric(5, 2) not null,
  fecha_inicio date not null,
  fecha_fin date not null,
  estado text not null default 'Activa',
  producto_id bigint not null references public.productos(id),
  imagen_url text
);
